### PR TITLE
[FIX] backup not ignored if force_version is set

### PR DESCRIPTION
**Pull request by sebalix**
<s>Didn't analyse further at this time to find the right fix.</s>
Fixed

### CODE REVIEW

**Comment by sebalix** [comment]
@guewen I'm reading this: https://github.com/camptocamp/marabunta/blob/aec896183715be9db5a07470eab4c728c70c22d8/marabunta/runner.py#L87-L100
Do you remember why do we want a backup if we force the version?

**Comment by guewen** [comment]
> Do you remember why do we want a backup if we force the version?

Probably an oversight: we want a backup **if the "ignore if" conditions are not met*.
The check for ignore_if is done individually in the versions, but it should be done in this particular case too.

BTW, this is where the check by version is done:

https://github.com/camptocamp/marabunta/blob/aec896183715be9db5a07470eab4c728c70c22d8/marabunta/model.py#L187

And it seems weird to me that it is repeated for every version as the result will be the same. It would be useful only if we could disable the backup conditionally on a version.

**Comment by mmequignon** [comment]
https://github.com/camptocamp/marabunta/blob/master/marabunta/runner.py#L91
@sebalix @guewen The issue is here, but it seems that it was wanted. Any idea why ?

**Comment by guewen** [comment]
@mmequignon answered in https://github.com/camptocamp/marabunta/pull/55#issuecomment-663469811

**Comment by mmequignon** [comment]
> @mmequignon answered in [#55 (comment)](https://github.com/camptocamp/marabunta/pull/55#issuecomment-663469811)

yes :(
Thanks

**Comment by sebalix** [comment]
@guewen fixed, but not sure if it's the best way?

**Comment by guewen** [comment]
From my reading of the code, but I may overlook something, it seems the best way would be to check this "ignore_if" operation only once, and not for every version when parsing the file.

Considering the parsing:

https://github.com/camptocamp/marabunta/blob/ec3a7a725c7426d6ed642e0a80119b37880eb91e/marabunta/parser.py#L196-L199


and this https://github.com/camptocamp/marabunta/blob/aec896183715be9db5a07470eab4c728c70c22d8/marabunta/model.py#L176-L189

First, I don't get why if `add_backup_operation()` receives `False` as `backup`, we are evaluating `self.options.backup.ignore_if_operation().execute()`. It seems to me if it receives `False`, it should just keep this value (the `backup` boolean option in a `version` was meant to explicitly flag a version as "safe", no need of a backup).
But then, evaluating `self.options.backup.ignore_if_operation().execute()` on each version is pointless. 

So, IMO `_parse_backup` should only set the `backup` flag of the `MarabuntaVersion` to `False` or `True` (defaulting to `True`).
Then, in the part of code you modified, we run `self.options.backup.ignore_if_operation().execute()` exactly once if at least one version has the `backup` flag or if we are forcing a version with the `backup` flag.

That being said, if you prefer, we can open an issue with this and already merge this fix.

**Comment by sebalix** [comment]
@guewen done
I dropped the `add_backup_operation` method to keep things simple, and the `ignore_if` option is checked only at the end if the a backup option has been found among versions.

**Review by guewen — APPROVED** [review]
Thanks! :green_heart:

**Comment by sebalix** [comment]
Rebased

**Review by jcoux — APPROVED** [review]
Technically seems good.

**Review by mmequignon — APPROVED** [review]
LG

**Pull request merged**
